[context.production.environment]
  REACT_APP_ENV = "production"

[build]
  base    = "web"
  command = "yarn run build"
  publish = "web/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200