Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Width: 2

Layout/TrailingBlankLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false